services:
	mysql:
		image: mysql:8.4
		container_name: smart-campus-mysql
		restart: unless-stopped
		ports:
			- "3306:3306"
		environment:
			MYSQL_ROOT_PASSWORD: root
			MYSQL_DATABASE: smart_campus
			MYSQL_USER: smartcampus_user
			MYSQL_PASSWORD: smartcampus_pass
		volumes:
			- mysql_data:/var/lib/mysql
		healthcheck:
			test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
			interval: 10s
			timeout: 5s
			retries: 10

volumes:
	mysql_data:
